name: Test self hosted runner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Build and Deploy
        run: |
          ls
          pwd
          echo "Thanh Le "
          git pull origin dev
