name: Test self hosted runner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Set up environment variables
        run: echo "${{ secrets.env }}" > /home/xbot/react-test-aws/.env
      - name: Build and Deploy
        run: |
          ls
          pwd
          echo "Thanh Le "
          cd /home/xbot/react-test-aws
          git pull origin master
          yarn && yarn build
          pm2 start deploy.json
