name: Test self hosted runner

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Build and Deploy
        run: |
          echo "Thanh Le "
          cd /home/sotatek/test
          pwd
          ls
