name: Auto deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build and Deploy
        env:
          host: '13.212.140.80' #hostname of server
          username: 'root' #username login to server
          port: '22' #port of server - often port is 22

        run: | # run with multiple script
          echo "Deploy"
          sudo cd /root/test
          sudo git clone git@github.com:Sotatek-ThanhLe2/react-test-aws.git
          cd react-test-aws
          git pull
          printf "${{ secrets.ENV }}" > .env
          pm2 start app.json
