name: Auto deploy

on:
  push:
    branches:
      - master1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            PRJ="${{ secrets.EC2_PRJ }}"
            DIR="${{ secrets.EC2_ROOT_DIR }}/$PRJ"

            if [ ! -d $DIR ]
            then
              mkdir ${PRJ} &&
              git clone ${{ secrets.EC2_HTTP_REPO_URL }} ${PRJ} &&
            fi

            cd ${PRJ}
            git checkout master
            git pull
            pm2 restart deploy.json
          '
