name: Deploy to Staging

on:
  push:
    branches:
      - master
env:
  PROJECT_NAME: 'React Test AWS'
  PATH_PROJECT: '/home/xbot/react-test-aws'
  GOOGLE_CHAT_WEBHOOK: 'https://chat.googleapis.com/v1/spaces/AAAAS0lkPa4/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=1zpesQKZyjY1_E8U6Bye1RHG5BIop4Hutt43xysAqHc'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Notify Google Chat - Trigger Merge with commit info and project name
      - name: Notify Google Chat - Trigger Merge
        run: |
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          COMMIT_AUTHOR="${{ github.actor }}"
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\": \"Project: ${PROJECT_NAME} - Author: ${COMMIT_AUTHOR}. Commit message: '${COMMIT_MESSAGE}'. [View commit here](${COMMIT_URL}).\"}" \
          $GOOGLE_CHAT_WEBHOOK

      # Step 2: Checkout code from the repository
      - name: Checkout code
        run: |
          cd $PATH_PROJECT
          git checkout master
          git pull origin master

      # Step 5: Set up environment variables
      - name: Set up environment variables
        run: echo "${{ secrets.env }}" > .env

      # Step 6: Build the Docker image
      - name: Build the Docker image
        run: |
          cd $PATH_PROJECT
          yarn && yarn build
        continue-on-error: false

      # Step 7: Notify Google Chat - Build Success
      - name: Notify Google Chat - Build Success
        if: success()

      # Step 8: Deploy to Staging
      - name: Deploy to Staging
        if: success()
        run: |
          cd $PATH_PROJECT
          pm2 restart deploy.json
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\": \"Project: ${PROJECT_NAME}. Build & Deploy successfully.\"}" \
          $GOOGLE_CHAT_WEBHOOK

      # Step 9: Notify Google Chat - Build Failed
      - name: Notify Google Chat - Build Failed
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\": \"Project: ${PROJECT_NAME}. Build & Deploy failed. Please check the logs!\"}" \
          $GOOGLE_CHAT_WEBHOOK
